# Generated by Django 4.1.6 on 2023-06-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('AUDIO', 'AUDIO'), ('DOCUMENT', 'DOCUMENT')], default='DOCUMENT', max_length=12),
        ),
    ]
