# Generated by Django 4.1.6 on 2023-06-20 11:57

import Notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Notes.models.media_storage),
        ),
    ]
